spring.application.name=backend

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/fullshelf}
spring.datasource.username=${DATABASE_USERNAME:fullshelf}
spring.datasource.password=${DATABASE_PASSWORD:changeme}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
